#!/bin/bash

cd /etc/swift
swift-ring-builder storage.builder create 18 3 1

while read line; do
name=`echo $line|awk -F '=' '{print $1}'`
value=`echo $line|awk -F '=' '{print $2}'`
case $name in
"datanode")
	zone=`echo $value|awk -F '|' '{print $1}'`
	ip=`echo $value|awk -F '|' '{print $2}'`
	swift_path=`echo $value|awk -F '|' '{print $3}'`
	weight=`echo $value|awk -F '|' '{print $4}'`
	swift-ring-builder storage.builder add $zone-$ip:6003/$swift_path $weight
;;
*)
;;
esac
done < $RING_CONF

swift-ring-builder storage.builder 
swift-ring-builder storage.builder rebalance

while read line; do
name=`echo $line|awk -F '=' '{print $1}'`
value=`echo $line|awk -F '=' '{print $2}'`
case $name in
"datanode")
	ip=`echo $value|awk -F '|' '{print $2}' `
	user=`echo $value|awk -F '|' '{print $5}' `
	scp /etc/swift/*.ring.gz $user@$ip:/etc/swift/
;;
*)
;;
esac
done < $RING_CONF

cd -
