#!/bin/bash

cd /etc/swift
RING_CONF="./Ring.conf"
swift-ring-builder account.builder create 18 3 1
swift-ring-builder container.builder create 18 3 1
swift-ring-builder object.builder create 18 3 1

while read line; do
name=`echo $line|awk -F '=' '{print $1}'`
value=`echo $line|awk -F '=' '{print $2}'`
case $name in
"metanode")
	zone=`echo $value|awk -F '|' '{print $1}'`
	ip=`echo $value|awk -F '|' '{print $2}'`
	series=`echo $value|awk -F '|' '{print $3}'`
	swift_path=`echo $value|awk -F '|' '{print $4}'`
	weight=`echo $value|awk -F '|' '{print $5}'`
	swift-ring-builder account.builder add $zone-$ip:60${series}2/$swift_path $weight
	swift-ring-builder container.builder add $zone-$ip:60${series}1/$swift_path $weight
	swift-ring-builder object.builder add $zone-$ip:60${series}0/$swift_path $weight
;;
*)
;;
esac
done < $RING_CONF

swift-ring-builder account.builder
swift-ring-builder container.builder 
swift-ring-builder object.builder 

swift-ring-builder account.builder rebalance
swift-ring-builder container.builder rebalance
swift-ring-builder object.builder rebalance

while read line; do
name=`echo $line|awk -F '=' '{print $1}'`
value=`echo $line|awk -F '=' '{print $2}'`
case $name in
"metanode")
	ip=`echo $value|awk -F '|' '{print $2}' `
	user=`echo $value|awk -F '|' '{print $6}' `
;;
*)
;;
esac
done < $RING_CONF
scp /etc/swift/*.ring.gz $user@$ip:/etc/swift/

cd -
