#!/bin/bash

source ./public.sh

export DISKS=(vdc vdd vde vdf)

apt-get install -y xfsprogs

for DISK in ${DISKS[@]};do
	umount /dev/$DISK
	mkfs.xfs -f -i size=512 /dev/$DISK
	mkdir -p /srv/node/$DISK
	mount -t xfs /dev/$DISK /srv/node/$DISK
done

apt-get install -y rsync

rm -f /etc/rsyncd.conf
cat >/etc/rsyncd.conf <<EOF
uid = root
gid = root 
log file = /var/log/rsyncd.log
pid file = /var/run/rsyncd.pid
address = $LOCAL_IP

EOF

for i in {1..4};do
cat >>/etc/rsyncd.conf <<EOF
[account60${i}2]
max connections = 25
path = /srv/node/
read only = false
lock file = /var/lock/account60${i}2.lock

[container60${i}1]
max connections = 25
path = /srv/node/
read only = false
lock file = /var/lock/container60${i}1.lock

[object60${i}0]
max connections = 25
path = /srv/node/
read only = false
lock file = /var/lock/object60${i}0.lock

EOF
done

perl -pi -e 's/RSYNC_ENABLE=false/RSYNC_ENABLE=true/' /etc/default/rsync

service rsync restart

rm -fr /etc/swift/account-server
rm -fr /etc/swift/container-server
rm -fr /etc/swift/object-server
mkdir -p /etc/swift/account-server
mkdir -p /etc/swift/container-server
mkdir -p /etc/swift/object-server

for i in {1..4};do
cat >/etc/swift/account-server/${i}.conf <<EOF
[DEFAULT]
mount_check = false
bind_ip = 0.0.0.0
user = root
workers = 2
bind_port = 60${i}2
log_facility = LOG_LOCAL3
recon_cache_path = /var/cache/swift${i}

[pipeline:main]
pipeline = recon account-server

[app:account-server]
use = egg:swift#account

[filter:recon]
use = egg:swift#recon

[account-replicator]

[account-auditor]

[account-reaper]
EOF

cat >/etc/swift/container-server/${i}.conf <<EOF
[DEFAULT]
mount_check = false
bind_ip = 0.0.0.0
user = root
workers = 2
bind_port = 60${i}1
log_facility = LOG_LOCAL2
recon_cache_path = /var/cache/swift${i}

[pipeline:main]
pipeline = recon container-server

[app:container-server]
use = egg:swift#container

[filter:recon]
use = egg:swift#recon

[container-replicator]

[container-updater]

[container-auditor]

[container-sync]
EOF

cat >/etc/swift/object-server/${i}.conf <<EOF
[DEFAULT]
mount_check = false
bind_ip = 0.0.0.0
user = root
workers = 2
bind_port = 60${i}0
log_facility = LOG_LOCAL1
disable_fallocate = true
recon_cache_path = /var/cache/swift${i}

[pipeline:main]
pipeline = recon object-server

[filter:recon]
use = egg:swift#recon

[app:object-server]
use = egg:swift#object

[object-replicator]

[object-updater]

[object-auditor]

[object-expirer]
EOF
done
