#!/bin/bash
sed -i s/[[:space:]]//g ./Ring.conf
cp ./Ring.conf /etc/swift/

cd /etc/swift
rm -f *.builder *.ring.gz backups/*.builder backups/*.ring.gz
cd -

RING_CONF="./Ring.conf"
source ./meta_ring
source ./data_ring

rm /etc/swift/Ring.conf
